#!/usr/bin/env bash

mkdir -p "/config/Plex Media Server/"
cp -n /Preferences.xml "/config/Plex Media Server/"
rm -f "/config/Plex Media Server/plexmediaserver.pid"

# Plex WebTools
if [ ! -d "/config/Plex Media Server/Plug-ins/WebTools.bundle" ]; then
	wt_tag=$(curl -sX GET "https://api.github.com/repos/ukdtom/WebTools.bundle/releases/latest" \
    	| awk '/tag_name/{print $4;exit}' FS='[""]')
	wget "https://github.com/ukdtom/WebTools.bundle/releases/download/$wt_tag/WebTools.bundle.zip" \
    	-O /config/Plex\ Media\ Server/Plug-ins/WebTools.bundle.zip
  	unzip /config/Plex\ Media\ Server/Plug-ins/WebTools.bundle.zip -d /config/Plex\ Media\ Server/Plug-ins/
  	rm -f /config/Plex\ Media\ Server/Plug-ins/WebTools.bundle.zip
fi

exec start_pms > /dev/null 2>&1