services:
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    restart: always
    volumes:
      - torrents:/torrents
      - configbazarr:/config
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}

volumes:
  configbazarr:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/bazarr