services:
  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      # - PASSWORD=${UN1K0RN_PASSWORD}
      # - CLI_ARGS=
    volumes:
      - configcalibre:/config
      - media:/data/media

volumes:
  configcalibre: 
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/calibre
