services:
  deluge:
    image: ghcr.io/linuxserver/deluge #:amd64-version-2.1.1-r6
    container_name: deluge
    restart: unless-stopped
    volumes:
      - configdeluge:/config
      - downloads:/data/media/downloads
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}

volumes:
  configdeluge: 
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/deluge