services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: duplicati
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - configduplicati:/config
      - backups:/backups
      - config:/source

volumes:
  configduplicati:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/duplicati
  backups:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/backups