services:
  flood:
    image: jesec/flood:master
    container_name: flood
    restart: unless-stopped
    depends_on:
      - deluge
    user: ${PUID}:${PGID}
    command:
      - --auth=none
      - --dehost=${DELUGE_HOST}
      - --deport=58846
      - --deuser=flood
      - --depass=${FLOOD_PASSWORD}
      - --rundir=/config
    volumes:
      - configflood:/config
      - downloads:/data/media/downloads
      - /etc/localtime:/etc/localtime:ro

volumes:
  configflood: 
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/flood