services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    restart: unless-stopped
    volumes:
      - configheimdall:/config
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}

volumes:
  configheimdall:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/heimdall