services:
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    restart: always
    volumes:
      - config:/config
      - torrents:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - RUN_OPTS='-FlareSolverrURL="http://flaresolverr:8191"'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.jackett.middlewares=common-auth@file"
