services:
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    volumes:
      - config:/config
      - media:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - RUN_OPTS='-FlareSolverrURL="http://flaresolverr:8191"'
