services:
  jdownloader:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    restart: unless-stopped
    volumes:
      - configjdownloader:/config
      - downloads:/output
    environment:
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}
      - TZ=${TZ}

volumes:
  configjdownloader:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/jdownloader