services:
  lidarr:
    image: ghcr.io/linuxserver/lidarr:develop
    container_name: lidarr
    restart: unless-stopped
    volumes:
      - configlidarr:/config
      - media:/data/media
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}

volumes:
  configlidarr:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/lidarr