services:
  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    restart: always
    volumes:
      - configombi:/config
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - BASE_URL=/

volumes:
  configombi:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/ombi