services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    restart: unless-stopped
    network_mode: host
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    devices:
      - /dev/dri:/dev/dri # for hardware transcoding
    volumes:
      - configplex:/config
      - media:/data/media
      - /dev/shm:/transcode
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - VERSION=latest

volumes:
  configplex:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/Plex