services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    volumes:
      - configprowlarr:/config
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}

volumes:
  configprowlarr:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/prowlarr