services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: always
    volumes:
      - configprowlarr:/config
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.prowlarr.middlewares=common-auth@file"

volumes:
  configprowlarr:
    driver: local-persist
    driver_opts:
      mountpoint: /data/config/prowlarr