services:
  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    restart: unless-stopped
    volumes:
      - configreadarr:/config
      - media:/data/media
      - /etc/localtime:/etc/localtime:ro
      - /data/config/readarr/scraper/certs/bookinfo-club.crt:/etc/ssl/certs/bookinfo-club.crt
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}

volumes:
  configreadarr: 
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/readarr
