services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr:develop
    container_name: sonarr
    restart: unless-stopped
    volumes:
      - configsonarr:/config
      - media:/data/media
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}


volumes:
  configsonarr: 
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/sonarr
