services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr:develop
    container_name: sonarr
    restart: always
    volumes:
      - configsonarr:/config
      - torrents:/torrents
      - library:/library
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}

volumes:
  configsonarr: 
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/sonarr
  library:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_LIBRARY_PATH
