services:
  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    restart: always
    volumes:
      - configtautulli:/config
      - config:/logs:ro # Inside of tautulli, bind to logs via "/logs/Plex Media Server/Logs"
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}

volumes:
  configtautulli:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/tautulli