#!/usr/bin/env bash

# Make rtorrent session directory
mkdir -p /config/rtorrent

# Add default config if it does not exist
cp -n /rtorrent.rc /config/rtorrent/rtorrent.rc

# Remove rtorrent lock file if it exists so rtorrent can start
rm -f /config/rtorrent/rtorrent.lock

# Make folders for storing rutorrent data
mkdir -p /config/rutorrent/settings /config/rutorrent/torrents \
    /config/rutorrent/users /config/rutorrent/plugins

exec supervisord -c /supervisord.conf
