#!/usr/bin/with-contenv sh

# Make rtorrent session directory
mkdir -p /config/rtorrent

# Add default config if it does not exist
cp -n /etc/defaults/rtorrent.rc /config/rtorrent/rtorrent.rc

# Make folders for storing rutorrent data
mkdir -p /config/rutorrent/settings /config/rutorrent/torrents \
    /config/rutorrent/users /config/rutorrent/plugins
